# The Open World Human Activity Recognition pipeline from given features
# extracted from a feature representaiton model to the end.
# This will probably be broken down into smaller chunks for convenience.

docstr:
  style: numpy
  from import:
    arn.data.docstr_workarounds:
      - get_steps
      - kinetics_owl_gmm_finch
    arn.data.kinetics_owl:
      - EvalConfig
      - EvalDataSplitConfig
      - DataSplits
      - KineticsOWL
      - KineticsOWLExperiment
    arn.data.kinetics_unified:
      - KineticsUnified
      - KineticsUnifiedFeatures
      - KineticsSplitConfig
      - KineticsUnifiedSubset
      - LabelConfig
      - BatchDirs
    arn.models.fine_tune:
      - FineTuneFC
    arn.models.fine_tune_lit:
      - FineTuneLit
      - FineTuneFCLit
      - init_trainer
      - init_ray_plugin
      - init_tensorboard_logger
    arn.models.predictor:
      - OWHAPredictor
    arn.models.novelty_recog.gaussian:
      - GaussianRecognizer
    arn.models.novelty_recog.gmm_finch:
      - GMMFINCH
  main: run
  log_sink: '/tmp/har/data/results/kowl/timesformer/test-run/gauss-recog/gmm_finch/label_recent_first/logs/log.log'
  log_level: DEBUG

kinetics_owl_gmm_finch: # Pipeline for the Open World Learning Data process
  eval_config:
    EvalConfig: # NOTE: the code seems to not even use pred_dir or eval_dir...
      root_dir: '/tmp/har/data/results/kowl/timesformer/test-run/gauss-recog/gmm_finch/label_recent_first/'
      train:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
      validate:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
      test:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
  post_feedback_eval_config:
    EvalConfig:
      root_dir: '/tmp/har/data/results/kowl/timesformer/test-run/gauss-recog/gmm_finch/label_recent_first/'
      train:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
      validate:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
      test:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
  maintain_experience: True
  predictor:
    GMMFINCH: # the Open World Agent
      #min_samples: 2
      #detect_error_tol: 1e-5
      min_error_tol: 0.05
      device: cpu
      dtype: float64
      cov_epsilon: 1e-12
      #dtype: float32
      #cov_epsilon: 1e-4
      threshold_func: min_max_threshold
      skip_fit: 0 # Does not use the FineTune ANN at all.
      load_inc_paths: /tmp/har/data/models/gmm_finch/min_err_tol_.005_threshold_global_bs8192/tsf_gmm_finch_feedback_1/chkpts/
      fine_tune:
        FineTuneLit:
          model:
            FineTuneFCLit:
              lr: 1e-3
              model:
                FineTuneFC:
                  input_size: 768
                  width: 768
                  depth: 1
                  dropout: 0.75
                  n_classes: 410
          batch_size: 1000
          trainer:
            init_trainer:
              max_epochs: 1
              log_every_n_steps: 1
              track_grad_norm: 2
              num_sanity_val_steps: 1
              gpus: 0
              enable_checkpointing: True
              default_root_dir: /tmp/har/data/results/kowl/timesformer/test-run/gauss-recog/gmm_finch/test-run/label_recent_first/chkpts/
              logger:
                init_tensorboard_logger:
                  save_dir: /tmp/har/data/results/kowl/timesformer/test-run/gauss-recog/gmm_finch/label_recent_first/tb_log/
  environment:
    KineticsOWLExperiment:
      inc_splits_per_dset: 5
      intro_freq_first: True
      start:
        DataSplits:
          train:
            KineticsUnifiedFeatures:
              blacklist: /tmp/har/data/kinetics/blacklists/blacklist-timesformer-kuni-uid.log
              annotation_path: /tmp/har/data/kinetics/kinetics_unified.csv
              sample_dirs:
                BatchDirs:
                  root_dir: /tmp/har/data/kinetics/features/timesformer/
                  batch_col: batch
              device: cpu # cuda
              dtype: float32
              subset:
                KineticsUnifiedSubset:
                  labels:
                    LabelConfig:
                      name: label_recent_first
                  kinetics400:
                    KineticsSplitConfig:
                      train: True
          validate:
            KineticsUnifiedFeatures:
              blacklist: /tmp/har/data/kinetics/blacklists/blacklist-timesformer-kuni-uid.log
              annotation_path: /tmp/har/data/kinetics/kinetics_unified.csv
              sample_dirs:
                BatchDirs:
                  root_dir: /tmp/har/data/kinetics/features/timesformer/
                  batch_col: batch
              device: cpu # cuda
              dtype: float32
              subset:
                KineticsUnifiedSubset:
                  labels:
                    LabelConfig:
                      name: label_recent_first
                  kinetics400:
                    KineticsSplitConfig:
                      validate: True
          test:
            KineticsUnifiedFeatures:
              blacklist: /tmp/har/data/kinetics/blacklists/blacklist-timesformer-kuni-uid.log
              annotation_path: /tmp/har/data/kinetics/kinetics_unified.csv
              sample_dirs:
                BatchDirs:
                  root_dir: /tmp/har/data/kinetics/features/timesformer/
                  batch_col: batch
              device: cpu # cuda
              dtype: float32
              subset:
                KineticsUnifiedSubset:
                  labels:
                    LabelConfig:
                      name: label_recent_first
                  kinetics400:
                    KineticsSplitConfig:
                      test: True
      steps:
        get_steps:
          step_1: # Kinetics 600
            DataSplits:
              train:
                KineticsUnifiedFeatures:
                  blacklist: /tmp/har/data/kinetics/blacklists/blacklist-timesformer-kuni-uid.log
                  annotation_path: /tmp/har/data/kinetics/kinetics_unified.csv
                  sample_dirs:
                    BatchDirs:
                      root_dir: /tmp/har/data/kinetics/features/timesformer/
                      batch_col: batch
                  device: cpu # cuda
                  dtype: float32
                  subset:
                    KineticsUnifiedSubset:
                      labels:
                        LabelConfig:
                          name: label_recent_first
                      kinetics600:
                        KineticsSplitConfig:
                          train: True
              validate:
                KineticsUnifiedFeatures:
                  blacklist: /tmp/har/data/kinetics/blacklists/blacklist-timesformer-kuni-uid.log
                  annotation_path: /tmp/har/data/kinetics/kinetics_unified.csv
                  sample_dirs:
                    BatchDirs:
                      root_dir: /tmp/har/data/kinetics/features/timesformer/
                      batch_col: batch
                  device: cpu # cuda
                  dtype: float32
                  subset:
                    KineticsUnifiedSubset:
                      labels:
                        LabelConfig:
                          name: label_recent_first
                      kinetics600:
                        KineticsSplitConfig:
                          validate: True
              test:
                KineticsUnifiedFeatures:
                  blacklist: /tmp/har/data/kinetics/blacklists/blacklist-timesformer-kuni-uid.log
                  annotation_path: /tmp/har/data/kinetics/kinetics_unified.csv
                  sample_dirs:
                    BatchDirs:
                      root_dir: /tmp/har/data/kinetics/features/timesformer/
                      batch_col: batch
                  device: cpu # cuda
                  dtype: float32
                  subset:
                    KineticsUnifiedSubset:
                      labels:
                        LabelConfig:
                          name: label_recent_first
                      kinetics600:
                        KineticsSplitConfig:
                          test: True

          step_2: # Kinetics 700-2020
            DataSplits:
              train:
                KineticsUnifiedFeatures:
                  blacklist: /tmp/har/data/kinetics/blacklists/blacklist-timesformer-kuni-uid.log
                  annotation_path: /tmp/har/data/kinetics/kinetics_unified.csv
                  sample_dirs:
                    BatchDirs:
                      root_dir: /tmp/har/data/kinetics/features/timesformer/
                      batch_col: batch
                  device: cpu # cuda
                  dtype: float32
                  subset:
                    KineticsUnifiedSubset:
                      labels:
                        LabelConfig:
                          name: label_recent_first
                      kinetics700_2020:
                        KineticsSplitConfig:
                          train: True
              test:
                KineticsUnifiedFeatures:
                  blacklist: /tmp/har/data/kinetics/blacklists/blacklist-timesformer-kuni-uid.log
                  annotation_path: /tmp/har/data/kinetics/kinetics_unified.csv
                  sample_dirs:
                    BatchDirs:
                      root_dir: /tmp/har/data/kinetics/features/timesformer/
                      batch_col: batch
                  device: cpu # cuda
                  dtype: float32
                  subset:
                    KineticsUnifiedSubset:
                      labels:
                        LabelConfig:
                          name: label_recent_first
                      kinetics700_2020:
                        KineticsSplitConfig:
                          validate: True
