# The Open World Human Activity Recognition pipeline from given features
# extracted from a feature representaiton model to the end. This will probably
# be broken down into smaller chunks for convenience.

docstr:
  style: numpy
  from import:
    arn.data.kinetics_owl:
      - EvalConfig
      - EvalDataSplitConfig
      - DataSplits
      - KineticsOWL
      - KineticsOWLExperiment
    arn.data.kinetics_unified:
      - KineticsUnified
      - KineticsUnifiedFeatures
      - KineticsSplitConfig
      - KineticsUnifiedSubset
      - LabelConfig
      - KineticsRootDirs
    arn.models.fine_tune:
      - FineTuneFC
    arn.models.fine_tune_lit:
      - FineTuneLit
      - FineTuneFCLit
      - init_trainer
      - init_ray_plugin
      - init_tensorboard_logger
    arn.models.owhar:
      - OWHAPredictor
  main: run #KineticsOWL.run
  log_sink: '/home/prijatelj/workspace/research/osr/repos/har/results/k400_start/x3d/fine-tune/logs/x3d_ftune.log'
  log_level: DEBUG

KineticsOWL: # Pipeline for the Open World Learning Data process
  eval_config:
    EvalConfig:
      root_dir: '/home/prijatelj/workspace/research/osr/repos/har/results/k400_start/x3d/fine-tune/'
      train:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
      validate:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
      test:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
  post_feedback_eval_config:
    EvalConfig:
      root_dir: '/home/prijatelj/workspace/research/osr/repos/har/results/k400_start/x3d/fine-tune/'
      train:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
      validate:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
      test:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
  environment:
    KineticsOWLExperiment:
      intro_freq_first: True
      start:
        DataSplits:
          train:
            KineticsUnifiedFeatures: #!docstr.configs:shared_data_kwargs
              blacklist: /home/prijatelj/workspace/research/osr/repos/har/data/kinetics400/x3d-k400-blacklist-train-file.log
              annotation_path: /home/prijatelj/workspace/research/osr/repos/har/data/analysis/kinetics/kinetics_400_600_700_2020.csv
              sample_dirs:
                KineticsRootDirs:
                  kinetics400_dir: x3d-features-k400/
                  kinetics600_dir: x3d-features-k600/
                  kinetics700_2020_dir: x3d-features-k700_2020/
                  root_dir: /mnt/hdd/workspace/research/osr/har/kitware/
              device: cuda
              dtype: float32
              subset:
                KineticsUnifiedSubset:
                  labels:
                    LabelConfig:
                      name: 'label_recent_first'
                  kinetics400:
                    KineticsSplitConfig:
                      train: True
          validate:
            KineticsUnifiedFeatures: #!docstr.configs:shared_data_kwargs
              blacklist: /home/prijatelj/workspace/research/osr/repos/har/data/kinetics400/x3d-k400-blacklist-val-file.log
              annotation_path: /home/prijatelj/workspace/research/osr/repos/har/data/analysis/kinetics/kinetics_400_600_700_2020.csv
              sample_dirs:
                KineticsRootDirs:
                  kinetics400_dir: x3d-features-k400/
                  kinetics600_dir: x3d-features-k600/
                  kinetics700_2020_dir: x3d-features-k700_2020/
                  root_dir: /mnt/hdd/workspace/research/osr/har/kitware/
              device: cuda
              dtype: float32
              subset:
                KineticsUnifiedSubset:
                  labels:
                    LabelConfig:
                      name: 'label_recent_first'
                  kinetics400:
                    KineticsSplitConfig:
                      validate: True
          test:
            KineticsUnifiedFeatures: #!docstr.configs:shared_data_kwargs
              blacklist: /home/prijatelj/workspace/research/osr/repos/har/data/kinetics400/x3d-k400-blacklist-test-file.log
              annotation_path: /home/prijatelj/workspace/research/osr/repos/har/data/analysis/kinetics/kinetics_400_600_700_2020.csv
              sample_dirs:
                KineticsRootDirs:
                  kinetics400_dir: x3d-features-k400/
                  kinetics600_dir: x3d-features-k600/
                  kinetics700_2020_dir: x3d-features-k700_2020/
                  root_dir: /mnt/hdd/workspace/research/osr/har/kitware/
              device: cuda
              dtype: float32
              subset:
                KineticsUnifiedSubset:
                  labels:
                    LabelConfig:
                      name: 'label_recent_first'
                  kinetics400:
                    KineticsSplitConfig:
                      test: True
      steps: # List of DataSplits consisting of KineticsUnified Datasets
        get_steps:
          step_1: # K600
            DataSplits:
              train:
                KineticsUnifiedFeatures: #!docstr.configs:shared_data_kwargs
                  blacklist: /home/prijatelj/workspace/research/osr/repos/har/data/kinetics400/x3d-k400-blacklist-train-file.log
                  annotation_path: /home/prijatelj/workspace/research/osr/repos/har/data/analysis/kinetics/kinetics_400_600_700_2020.csv
                  sample_dirs:
                    KineticsRootDirs:
                      kinetics400_dir: x3d-features-k400/
                      kinetics600_dir: x3d-features-k600/
                      kinetics700_2020_dir: x3d-features-k700_2020/
                      root_dir: /mnt/hdd/workspace/research/osr/har/kitware/
                  device: cuda
                  dtype: float32
                  subset:
                    KineticsUnifiedSubset:
                      labels:
                        LabelConfig:
                          name: 'label_recent_first'
                      kinetics600:
                        KineticsSplitConfig:
                          train: True
              validate:
                KineticsUnifiedFeatures: #!docstr.configs:shared_data_kwargs
                  blacklist: /home/prijatelj/workspace/research/osr/repos/har/data/kinetics400/x3d-k400-blacklist-val-file.log
                  annotation_path: /home/prijatelj/workspace/research/osr/repos/har/data/analysis/kinetics/kinetics_400_600_700_2020.csv
                  sample_dirs:
                    KineticsRootDirs:
                      kinetics400_dir: x3d-features-k400/
                      kinetics600_dir: x3d-features-k600/
                      kinetics700_2020_dir: x3d-features-k700_2020/
                      root_dir: /mnt/hdd/workspace/research/osr/har/kitware/
                  device: cuda
                  dtype: float32
                  subset:
                    KineticsUnifiedSubset:
                      labels:
                        LabelConfig:
                          name: 'label_recent_first'
                      kinetics600:
                        KineticsSplitConfig:
                          validate: True
              test:
                KineticsUnifiedFeatures: #!docstr.configs:shared_data_kwargs
                  blacklist: /home/prijatelj/workspace/research/osr/repos/har/data/kinetics400/x3d-k400-blacklist-test-file.log
                  annotation_path: /home/prijatelj/workspace/research/osr/repos/har/data/analysis/kinetics/kinetics_400_600_700_2020.csv
                  sample_dirs:
                    KineticsRootDirs:
                      kinetics400_dir: x3d-features-k400/
                      kinetics600_dir: x3d-features-k600/
                      kinetics700_2020_dir: x3d-features-k700_2020/
                      root_dir: /mnt/hdd/workspace/research/osr/har/kitware/
                  device: cuda
                  dtype: float32
                  subset:
                    KineticsUnifiedSubset:
                      labels:
                        LabelConfig:
                          name: 'label_recent_first'
                      kinetics600:
                        KineticsSplitConfig:
                          test: True
          step_2:
            DataSplits:
              train:
                KineticsUnifiedFeatures: #!docstr.configs:shared_data_kwargs
                  blacklist: /home/prijatelj/workspace/research/osr/repos/har/data/kinetics400/x3d-k400-blacklist-train-file.log
                  annotation_path: /home/prijatelj/workspace/research/osr/repos/har/data/analysis/kinetics/kinetics_400_600_700_2020.csv
                  sample_dirs:
                    KineticsRootDirs:
                      kinetics400_dir: x3d-features-k400/
                      kinetics600_dir: x3d-features-k600/
                      kinetics700_2020_dir: x3d-features-k700_2020/
                      root_dir: /mnt/hdd/workspace/research/osr/har/kitware/
                  device: cuda
                  dtype: float32
                  subset:
                    KineticsUnifiedSubset:
                      labels:
                        LabelConfig:
                          name: 'label_recent_first'
                      kinetics700:
                        KineticsSplitConfig:
                          train: True
              validate:
                KineticsUnifiedFeatures: #!docstr.configs:shared_data_kwargs
                  blacklist: /home/prijatelj/workspace/research/osr/repos/har/data/kinetics400/x3d-k400-blacklist-val-file.log
                  annotation_path: /home/prijatelj/workspace/research/osr/repos/har/data/analysis/kinetics/kinetics_400_600_700_2020.csv
                  sample_dirs:
                    KineticsRootDirs:
                      kinetics400_dir: x3d-features-k400/
                      kinetics600_dir: x3d-features-k600/
                      kinetics700_2020_dir: x3d-features-k700_2020/
                      root_dir: /mnt/hdd/workspace/research/osr/har/kitware/
                  device: cuda
                  dtype: float32
                  subset:
                    KineticsUnifiedSubset:
                      labels:
                        LabelConfig:
                          name: 'label_recent_first'
                      kinetics700:
                        KineticsSplitConfig:
                          validate: True
              test:
                KineticsUnifiedFeatures: #!docstr.configs:shared_data_kwargs
                  blacklist: /home/prijatelj/workspace/research/osr/repos/har/data/kinetics400/x3d-k400-blacklist-test-file.log
                  annotation_path: /home/prijatelj/workspace/research/osr/repos/har/data/analysis/kinetics/kinetics_400_600_700_2020.csv
                  sample_dirs:
                    KineticsRootDirs:
                      kinetics400_dir: x3d-features-k400/
                      kinetics600_dir: x3d-features-k600/
                      kinetics700_2020_dir: x3d-features-k700_2020/
                      root_dir: /mnt/hdd/workspace/research/osr/har/kitware/
                  device: cuda
                  dtype: float32
                  subset:
                    KineticsUnifiedSubset:
                      labels:
                        LabelConfig:
                          name: 'label_recent_first'
                      kinetics700:
                        KineticsSplitConfig:
                          test: True
  predictor:
    OWHAPredictor: # the Open World Agent
      fine_tune:
        FineTuneLit:
          model:
            FineTuneFCLit:
              model:
                FineTuneFC:
                  input_size: 2048 #512
                  width: 512
                  depth: 1
                  dropout: 0.75
                  n_classes: 401
          batch_size: 1000
          trainer:
            init_trainer:
              max_epochs: 25
              gpus: 1
              enable_checkpointing: True
              default_root_dir: /home/prijatelj/workspace/research/osr/repos/har/results/k400_start/x3d/fine-tune/chkpts/
              logger:
                init_tensorboard_logger:
                  save_dir: /home/prijatelj/workspace/research/osr/repos/har/results/k400_start/x3d/fine-tune/tb_log/
      #novelty_detector: None # Classification + Clustering
