# The Open World Human Activity Recognition pipeline from given features
# extracted from a feature representaiton model to the end. This will probably
# be broken down into smaller chunks for convenience.

docstr:
  style: numpy
  from import:
    arn.data.kinetics_owl:
      - EvalConfig
      - EvalDataSplitConfig
      - DataSplits
      - KineticsOWL
      - KineticsOWLExperiment
      - get_steps
    arn.data.kinetics_unified:
      - KineticsUnified
      - KineticsUnifiedFeatures
      - KineticsSplitConfig
      - KineticsUnifiedSubset
      - LabelConfig
      - BatchDirs
    arn.models.fine_tune:
      - FineTuneFC
    arn.models.fine_tune_lit:
      - FineTuneLit
      - FineTuneFCLit
      - init_trainer
      - init_ray_plugin
      - init_tensorboard_logger
    arn.models.owhar:
      - OWHAPredictor
  main: run
  log_sink: '/mnt/hdd/workspace/research/osr/har/results/kowl/x3d/test-run/fine-tune/label_recent_first/logs/log.log'
  log_level: DEBUG

KineticsOWL: # Pipeline for the Open World Learning Data process
  eval_config:
    EvalConfig: # NOTE: the code seems to not even use pred_dir or eval_dir...
      root_dir: '/mnt/hdd/workspace/research/osr/har/results/kowl/x3d/test-run/fine-tune/label_recent_first/'
      train:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
      validate:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
      test:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
  post_feedback_eval_config:
    EvalConfig:
      root_dir: '/mnt/hdd/workspace/research/osr/har/results/kowl/x3d/test-run/fine-tune/label_recent_first/'
      train:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
      validate:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
      test:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
  maintain_experience: True
  predictor:
    OWHAPredictor: # the Open World Agent
      fine_tune:
        FineTuneLit:
          model:
            FineTuneFCLit:
              lr: 1e-3
              model:
                FineTuneFC:
                  input_size: 8192
                  width: 2048
                  depth: 1
                  dropout: 0.75
                  n_classes: 410
          batch_size: 1000
          trainer:
            init_trainer:
              max_epochs: 1
              log_every_n_steps: 1
              track_grad_norm: 2
              num_sanity_val_steps: 1
              gpus: 1
              enable_checkpointing: True
              default_root_dir: /mnt/hdd/workspace/research/osr/har/results/kowl/x3d/test-run/fine-tune/label_recent_first/chkpts/
              logger:
                init_tensorboard_logger:
                  save_dir: /mnt/hdd/workspace/research/osr/har/results/kowl/x3d/test-run/fine-tune/label_recent_first/tb_log/
      #novelty_detector: None # Classification + Clustering
  environment:
    KineticsOWLExperiment:
      inc_splits_per_dset: 10
      intro_freq_first: True
      start:
        DataSplits:
          train:
            KineticsUnifiedFeatures:
              post_load: flatten
              blacklist: /home/prijatelj/workspace/research/osr/repos/har/data/blacklists/x3d/blacklist-x3d-kuni-uid.log
              annotation_path: /mnt/hdd/workspace/research/osr/har/kinetics_unified.csv
              sample_dirs:
                BatchDirs:
                  root_dir: /home/prijatelj/workspace/research/osr/repos/har/data/features/x3d/
                  batch_col: batch
              device: cuda
              dtype: float32
              subset:
                KineticsUnifiedSubset:
                  labels:
                    LabelConfig:
                      name: label_recent_first
                  kinetics400:
                    KineticsSplitConfig:
                      train: True
          validate:
            KineticsUnifiedFeatures:
              post_load: flatten
              blacklist: /home/prijatelj/workspace/research/osr/repos/har/data/blacklists/x3d/blacklist-x3d-kuni-uid.log
              annotation_path: /mnt/hdd/workspace/research/osr/har/kinetics_unified.csv
              sample_dirs:
                BatchDirs:
                  root_dir: /home/prijatelj/workspace/research/osr/repos/har/data/features/x3d/
                  batch_col: batch
              device: cuda
              dtype: float32
              subset:
                KineticsUnifiedSubset:
                  labels:
                    LabelConfig:
                      name: label_recent_first
                  kinetics400:
                    KineticsSplitConfig:
                      validate: True
          test:
            KineticsUnifiedFeatures:
              post_load: flatten
              blacklist: /home/prijatelj/workspace/research/osr/repos/har/data/blacklists/x3d/blacklist-x3d-kuni-uid.log
              annotation_path: /mnt/hdd/workspace/research/osr/har/kinetics_unified.csv
              sample_dirs:
                BatchDirs:
                  root_dir: /home/prijatelj/workspace/research/osr/repos/har/data/features/x3d/
                  batch_col: batch
              device: cuda
              dtype: float32
              subset:
                KineticsUnifiedSubset:
                  labels:
                    LabelConfig:
                      name: label_recent_first
                  kinetics400:
                    KineticsSplitConfig:
                      test: True
      steps:
        get_steps:
          step_1: # Kinetics 600
            DataSplits:
              train:
                KineticsUnifiedFeatures:
                  post_load: flatten
                  blacklist: /home/prijatelj/workspace/research/osr/repos/har/data/blacklists/x3d/blacklist-x3d-kuni-uid.log
                  annotation_path: /mnt/hdd/workspace/research/osr/har/kinetics_unified.csv
                  sample_dirs:
                    BatchDirs:
                      root_dir: /home/prijatelj/workspace/research/osr/repos/har/data/features/x3d/
                      batch_col: batch
                  device: cuda
                  dtype: float32
                  subset:
                    KineticsUnifiedSubset:
                      labels:
                        LabelConfig:
                          name: label_recent_first
                      kinetics600:
                        KineticsSplitConfig:
                          train: True
              validate:
                KineticsUnifiedFeatures:
                  post_load: flatten
                  blacklist: /home/prijatelj/workspace/research/osr/repos/har/data/blacklists/x3d/blacklist-x3d-kuni-uid.log
                  annotation_path: /mnt/hdd/workspace/research/osr/har/kinetics_unified.csv
                  sample_dirs:
                    BatchDirs:
                      root_dir: /home/prijatelj/workspace/research/osr/repos/har/data/features/x3d/
                      batch_col: batch
                  device: cuda
                  dtype: float32
                  subset:
                    KineticsUnifiedSubset:
                      labels:
                        LabelConfig:
                          name: label_recent_first
                      kinetics600:
                        KineticsSplitConfig:
                          validate: True
              test:
                KineticsUnifiedFeatures:
                  post_load: flatten
                  blacklist: /home/prijatelj/workspace/research/osr/repos/har/data/blacklists/x3d/blacklist-x3d-kuni-uid.log
                  annotation_path: /mnt/hdd/workspace/research/osr/har/kinetics_unified.csv
                  sample_dirs:
                    BatchDirs:
                      root_dir: /home/prijatelj/workspace/research/osr/repos/har/data/features/x3d/
                      batch_col: batch
                  device: cuda
                  dtype: float32
                  subset:
                    KineticsUnifiedSubset:
                      labels:
                        LabelConfig:
                          name: label_recent_first
                      kinetics600:
                        KineticsSplitConfig:
                          test: True

          step_2: # Kinetics 700-2020
            DataSplits:
              train:
                KineticsUnifiedFeatures:
                  post_load: flatten
                  blacklist: /home/prijatelj/workspace/research/osr/repos/har/data/blacklists/x3d/blacklist-x3d-kuni-uid.log
                  annotation_path: /mnt/hdd/workspace/research/osr/har/kinetics_unified.csv
                  sample_dirs:
                    BatchDirs:
                      root_dir: /home/prijatelj/workspace/research/osr/repos/har/data/features/x3d/
                      batch_col: batch
                  device: cuda
                  dtype: float32
                  subset:
                    KineticsUnifiedSubset:
                      labels:
                        LabelConfig:
                          name: label_recent_first
                      kinetics700_2020:
                        KineticsSplitConfig:
                          train: True
              validate:
                KineticsUnifiedFeatures:
                  post_load: flatten
                  blacklist: /home/prijatelj/workspace/research/osr/repos/har/data/blacklists/x3d/blacklist-x3d-kuni-uid.log
                  annotation_path: /mnt/hdd/workspace/research/osr/har/kinetics_unified.csv
                  sample_dirs:
                    BatchDirs:
                      root_dir: /home/prijatelj/workspace/research/osr/repos/har/data/features/x3d/
                      batch_col: batch
                  device: cuda
                  dtype: float32
                  subset:
                    KineticsUnifiedSubset:
                      labels:
                        LabelConfig:
                          name: label_recent_first
                      kinetics700_2020:
                        KineticsSplitConfig:
                          validate: True
              test:
                KineticsUnifiedFeatures:
                  post_load: flatten
                  blacklist: /home/prijatelj/workspace/research/osr/repos/har/data/blacklists/x3d/blacklist-x3d-kuni-uid.log
                  annotation_path: /mnt/hdd/workspace/research/osr/har/kinetics_unified.csv
                  sample_dirs:
                    BatchDirs:
                      root_dir: /home/prijatelj/workspace/research/osr/repos/har/data/features/x3d/
                      batch_col: batch
                  device: cuda
                  dtype: float32
                  subset:
                    KineticsUnifiedSubset:
                      labels:
                        LabelConfig:
                          name: label_recent_first
                      kinetics700_2020:
                        KineticsSplitConfig:
                          test: True
