# The Open World Human Activity Recognition pipeline from given features
# extracted from a feature representaiton model to the end. This will probably
# be broken down into smaller chunks for convenience.

docstr:
  style: numpy
  from import:
    arn.data.kinetics_owl:
      - EvalConfig
      - EvalDataSplitConfig
      - DataSplits
      - KineticsOWL
      - KineticsOWLExperiment
    arn.data.kinetics_unified:
      - KineticsUnified
      - KineticsUnifiedFeatures
      - KineticsSplitConfig
      - KineticsUnifiedSubset
      - LabelConfig
      - KineticsRootDirs
      - BatchDirs
    arn.models.fine_tune:
      - FineTuneFC
    arn.models.fine_tune_lit:
      - FineTuneLit
      - FineTuneFCLit
      - init_trainer
      - init_ray_plugin
      - init_tensorboard_logger
    arn.models.owhar:
      - OWHAPredictor
  main: run #KineticsOWL.run
  log_sink: stdout
  log_level: DEBUG

KineticsOWL: # Pipeline for the Open World Learning Data process
  eval_config:
    EvalConfig:
      root_dir: '/home/prijatelj/workspace/research/osr/repos/har/results/k400_start/x3d/fine-tune/'
      train:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
      validate:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
      test:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
  post_feedback_eval_config:
    EvalConfig:
      root_dir: '/home/prijatelj/workspace/research/osr/repos/har/results/k400_start/x3d/fine-tune/'
      train:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
      validate:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
      test:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
  environment:
    KineticsOWLExperiment:
      start:
        DataSplits:
          train:
            KineticsUnifiedFeatures:
              post_load: flatten
              blacklist: /home/prijatelj/workspace/research/osr/repos/har/data/blacklists/x3d/blacklist-x3d-kuni-uid.log
              annotation_path: /mnt/hdd/workspace/research/osr/har/kinetics_unified_batched_recent_first.csv
              sample_dirs:
                BatchDirs:
                  root_dir: /home/prijatelj/workspace/research/osr/repos/har/data/features/x3d/
                  batch_col: batch
              device: cuda
              dtype: float32
              subset:
                KineticsUnifiedSubset:
                  labels:
                    LabelConfig:
                      name: label_recent_first #'label_kinetics400'
                  kinetics400:
                    KineticsSplitConfig:
                      train: True
          validate:
            KineticsUnifiedFeatures: #!docstr.configs:shared_data_kwargs
              post_load: flatten
              blacklist: /home/prijatelj/workspace/research/osr/repos/har/data/blacklists/x3d/blacklist-x3d-kuni-uid.log
              annotation_path: /mnt/hdd/workspace/research/osr/har/kinetics_unified_batched_recent_first.csv
              sample_dirs:
                BatchDirs:
                  root_dir: /home/prijatelj/workspace/research/osr/repos/har/data/features/x3d/
                  batch_col: batch_x3d
              device: cuda
              dtype: float32
              subset:
                KineticsUnifiedSubset:
                  labels:
                    LabelConfig:
                      name: label_recent_first #'label_kinetics400'
                  kinetics400:
                    KineticsSplitConfig:
                      validate: True
          test:
            KineticsUnifiedFeatures: #!docstr.configs:shared_data_kwargs
              post_load: flatten
              blacklist: /home/prijatelj/workspace/research/osr/repos/har/data/blacklists/x3d/blacklist-x3d-kuni-uid.log
              annotation_path: /mnt/hdd/workspace/research/osr/har/kinetics_unified_batched_recent_first.csv
              sample_dirs:
                BatchDirs:
                  root_dir: /home/prijatelj/workspace/research/osr/repos/har/data/features/x3d/
                  batch_col: batch_x3d
              device: cuda
              dtype: float32
              subset:
                KineticsUnifiedSubset:
                  labels:
                    LabelConfig:
                      name: label_recent_first #'label_kinetics400'
                  kinetics400:
                    KineticsSplitConfig:
                      test: True
  predictor:
    OWHAPredictor: # the Open World Agent
      fine_tune:
        FineTuneLit:
          model:
            FineTuneFCLit:
              model:
                FineTuneFC:
                  input_size: 2048
                  width: 2048
                  depth: 1
                  dropout: 0.75
                  n_classes: 401
          batch_size: 1000
          trainer:
            init_trainer:
              max_epochs: 25
              gpus: 1
              enable_checkpointing: True
              default_root_dir: /home/prijatelj/workspace/research/osr/repos/har/results/k400_start/x3d/fine-tune/chkpts/
              logger:
                init_tensorboard_logger:
                  save_dir: /home/prijatelj/workspace/research/osr/repos/har/results/k400_start/x3d/fine-tune/tb_log/
      #novelty_detector: None # Classification + Clustering
