# The Open World Human Activity Recognition pipeline from given features
# extracted from a feature representaiton model to the end. This will probably
# be broken down into smaller chunks for convenience.

docstr:
  style: numpy
  from import:
    arn.data.kinetics_owl:
      - EvalConfig
      - EvalDataSplitConfig
      - DataSplits
      - KineticsOWL
      - KineticsOWLExperiment
      - kinetics_owl_evm
    arn.data.kinetics_unified:
      - KineticsUnified
      - KineticsUnifiedFeatures
      - KineticsSplitConfig
      - KineticsUnifiedSubset
      - LabelConfig
      - BatchDirs
    arn.models.fine_tune:
      - FineTuneFC
    arn.models.fine_tune_lit:
      - FineTuneLit
      - FineTuneFCLit
      - init_trainer
      - init_ray_plugin
      - init_tensorboard_logger
    arn.models.owhar:
      - EVMPredictor
  main: run #KineticsOWL.run
  log_sink: stdout
  log_level: DEBUG

kinetics_owl_evm: # Pipeline for the Open World Learning Data process
  predictor: # the Open World Agent
    EVMPredictor:
      tail_size: 100
      cover_threshold: 0.7
      distance_multiplier: 1.0
      distance_metric: cosine
      labels: /mnt/hdd/workspace/research/osr/har/sim_classify/labels_sim_k400.csv
      device: cpu
      dtype: float32
      chunk_size: 1
      atol: 1e-5
      save_dir: /mnt/hdd/workspace/research/osr/har/results/sim_owr/exp1_2d_sim/evm/
  eval_config:
    EvalConfig:
      root_dir: '/mnt/hdd/workspace/research/osr/har/results/sim_owr/exp1_2d_sim/evm/'
      train:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
      validate:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
      test:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
  post_feedback_eval_config:
    EvalConfig:
      root_dir: '/mnt/hdd/workspace/research/osr/har/results/sim_owr/exp1_2d_sim/evm/'
      train:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
      validate:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
      test:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
  environment:
    KineticsOWLExperiment:
      start:
        DataSplits:
          train:
            KineticsUnifiedFeatures: #!docstr.configs:shared_data_kwargs
              annotation_path: /mnt/hdd/workspace/research/osr/har/sim_classify/sim_kunified.csv
              sample_dirs:
                BatchDirs:
                  batch_col: batch
                  root_dir: /mnt/hdd/workspace/research/osr/har/sim_classify/
              device: cuda
              dtype: float32
              split_prefix: False
              k700_suffix_label: False
              subset:
                KineticsUnifiedSubset:
                  labels:
                    LabelConfig:
                      name: 'label_kinetics400'
                  kinetics400:
                    KineticsSplitConfig:
                      train: True
          validate:
            KineticsUnifiedFeatures: #!docstr.configs:shared_data_kwargs
              annotation_path: /mnt/hdd/workspace/research/osr/har/sim_classify/sim_kunified.csv
              split_prefix: False
              k700_suffix_label: False
              sample_dirs:
                BatchDirs:
                  batch_col: batch
                  root_dir: /mnt/hdd/workspace/research/osr/har/sim_classify/
              device: cuda
              dtype: float32
              subset:
                KineticsUnifiedSubset:
                  labels:
                    LabelConfig:
                      name: 'label_kinetics400'
                  kinetics400:
                    KineticsSplitConfig:
                      validate: True
          test:
            KineticsUnifiedFeatures: #!docstr.configs:shared_data_kwargs
              annotation_path: /mnt/hdd/workspace/research/osr/har/sim_classify/sim_kunified.csv
              split_prefix: False
              k700_suffix_label: False
              sample_dirs:
                BatchDirs:
                  batch_col: batch
                  root_dir: /mnt/hdd/workspace/research/osr/har/sim_classify/
              device: cuda
              dtype: float32
              subset:
                KineticsUnifiedSubset:
                  labels:
                    LabelConfig:
                      name: 'label_kinetics400'
                  kinetics400:
                    KineticsSplitConfig:
                      test: True
