# The Open World Human Activity Recognition pipeline from given features
# extracted from a feature representaiton model to the end. This will probably
# be broken down into smaller chunks for convenience.

docstr:
  style: numpy
  from import:
    arn.data.kinetics_owl:
      - EvalConfig
      - EvalDataSplitConfig
      - DataSplits
      - KineticsOWL
      - KineticsOWLExperiment
    arn.data.kinetics_unified:
      - KineticsUnified
      - KineticsUnifiedFeatures
      - KineticsSplitConfig
      - KineticsUnifiedSubset
      - LabelConfig
      - KineticsRootDirs
    arn.models.fine_tune:
      - FineTuneFC
    arn.models.fine_tune_lit:
      - FineTuneLit
      - FineTuneFCLit
      - init_trainer
      - init_ray_plugin
      - init_tensorboard_logger
    arn.models.novelty_detector:
      - WindowedMeanKLDiv
    arn.models.owhar:
      - OWHAPredictor
  main: run #KineticsOWL.run
  log_sink: stdout
  log_level: DEBUG

KineticsOWL: # Pipeline for the Open World Learning Data process
  eval_config:
    EvalConfig:
      root_dir: '/home/prijatelj/workspace/research/osr/repos/har/results/sim_owr/exp1_2d_sim/fine-tune/'
      train:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
      validate:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
      test:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
  post_feedback_eval_config:
    EvalConfig:
      root_dir: '/home/prijatelj/workspace/research/osr/repos/har/results/sim_owr/exp1_2d_sim/fine-tune/'
      train:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
      validate:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
      test:
        EvalDataSplitConfig:
          pred_dir: 'preds/'
          eval_dir: 'eval/'
  environment:
    KineticsOWLExperiment:
      start:
        DataSplits:
          train:
            KineticsUnifiedFeatures: #!docstr.configs:shared_data_kwargs
              annotation_path: /mnt/hdd/workspace/research/osr/har/sim_classify/sim_kunified.csv
              sample_dirs:
                KineticsRootDirs:
                  kinetics400_dir: sim_k400/
                  kinetics600_dir: sim_k600/
                  kinetics700_2020_dir: sim_k700/
                  root_dir: /mnt/hdd/workspace/research/osr/har/sim_classify/
              device: cuda
              dtype: float32
              split_prefix: False
              k700_suffix_label: False
              subset:
                KineticsUnifiedSubset:
                  labels:
                    LabelConfig:
                      name: 'label_kinetics400'
                  kinetics400:
                    KineticsSplitConfig:
                      train: True
          validate:
            KineticsUnifiedFeatures: #!docstr.configs:shared_data_kwargs
              annotation_path: /mnt/hdd/workspace/research/osr/har/sim_classify/sim_kunified.csv
              split_prefix: False
              k700_suffix_label: False
              sample_dirs:
                KineticsRootDirs:
                  kinetics400_dir: sim_k400/
                  kinetics600_dir: sim_k600/
                  kinetics700_2020_dir: sim_k700/
                  root_dir: /mnt/hdd/workspace/research/osr/har/sim_classify/
              device: cuda
              dtype: float32
              subset:
                KineticsUnifiedSubset:
                  labels:
                    LabelConfig:
                      name: 'label_kinetics400'
                  kinetics400:
                    KineticsSplitConfig:
                      validate: True
          test:
            KineticsUnifiedFeatures: #!docstr.configs:shared_data_kwargs
              annotation_path: /mnt/hdd/workspace/research/osr/har/sim_classify/sim_kunified.csv
              split_prefix: False
              k700_suffix_label: False
              sample_dirs:
                KineticsRootDirs:
                  kinetics400_dir: sim_k400/
                  kinetics600_dir: sim_k600/
                  kinetics700_2020_dir: sim_k700/
                  root_dir: /mnt/hdd/workspace/research/osr/har/sim_classify/
              device: cuda
              dtype: float32
              subset:
                KineticsUnifiedSubset:
                  labels:
                    LabelConfig:
                      name: 'label_kinetics400'
                  kinetics400:
                    KineticsSplitConfig:
                      test: True
  predictor:
    OWHAPredictor: # the Open World Agent
      fine_tune:
        FineTuneLit:
          model:
            FineTuneFCLit:
              model:
                FineTuneFC:
                  input_size: 2 #512
                  width: 512
                  depth: 5
                  dropout: 0.5
                  n_classes: 5 # PAR's is 29, TODO wish docstr had lazy init,
                  #   could make input and output dependent on the experiment's
                  #   data at start.
          batch_size: 1000
          #device: 'cuda'
          # num_workers: 16
          # PytorchLightning.Trainer kwargs TODO parse unknown kwargs
          # Could add another docstr tag: docstr.parse_kwargs for unknown args
          # handled as YAML defaults or use other tags if provided or
          # necessary.
          # OR could just add a kwargs key w/ dict value and know to expand
          # that when passed.
          trainer:
            init_trainer:
              max_epochs: 25
              gpus: 1
              enable_checkpointing: True
              default_root_dir: /home/prijatelj/workspace/research/osr/repos/har/results/sim_owr/exp1_2d_sim/fine-tune/chkpts/
              #strategy:
              #  init_ray_plugin:
              #    num_workers: 8
              #    use_gpu: True
              logger:
                init_tensorboard_logger:
                  save_dir: /home/prijatelj/workspace/research/osr/repos/har/results/sim_owr/exp1_2d_sim/fine-tune/tb_log/
      novelty_detector: # Classification + Clustering
        WindowedMeanKLDiv:
          kl_threshold: 5.365822113508410
          kl_threshold_decay_rate: 0.6
          mean_train: 1.0
          std_dev_train: 0.1242729408792351
          window_size: 100
          num_rounds: 40
          #threshold_scale: 3.0 # Hack to scale down early detection.
          #feedback_weight: 1.0 # binary novelty feedback
