# The Open World Human Activity Recognition pipeline from given features
# extracted from a feature representaiton model to the end. This will probably
# be broken down into smaller chunks for convenience.

docstr:
  style: numpy
  from import:
    arn.data.kinetics_owl:
      - KineticsOWL
      - KineticsOWLExperiment
    arn.data.kinetics_unified:
      - KineticsUnifiedFeatures
      - KineticsSplitConfig
      - KineticsUnifiedSubset
      - LabelConfig
      - KineticsRootDirs
    arn.models.fine_tune:
      - FineTune
      - FineTuneFC
    arn.models.novelty_detector:
      - WindowedMeanKLDiv
    arn.models.owhar:
      - OWHAPredictor
  #import:
  #  - torch
  # config: # TODO add configuration file linking for convenience
  #   TimeSformer_features_dataloader: abs/path/to/the/config_file.yaml
  main: run #KineticsOWL.run

KineticsOWL: # Pipeline for the Open World Learning Data process
  seed: 0
  environment:
    KineticsOWLExperiment:
      shared_dataloader_kwargs:
        annotation_path: $HOME/workspace/research/osr/repos/har/data/analysis/kinetics/kinetics_400_600_700_2020.csv
        kinetics_class_map: # TODO add location of file.
        sample_dirs:
          kinetics400_dir: x3d-features-k400/
          kinetics600_dir: x3d-features-k600/
          kinetics700_2020_dir: x3d-features-k700_2020/
          # Support Environment Variables in config.
          root_dir: $HOME/workspace/research/osr/repos/har/data
      start:
        KineticsUnifiedFeatures:
          subset:
            KineticsUnifiedSubset:
              kinetics400:
                KineticsSplitConfig:
                  train: True
                  validate: True
                  test: True
    label_id: 'kinetics700_map' # TODO check if any k400 are cut. or other changes.
  predictor:
    OWHAPredictor: # the Open World Agent
      fine_tuning:
        FineTune:
          model:
            FineTuneFC:
              input_size: 512
              width: 512
              depth: 5
              dropout: 0.5
          batch_size: 1000
          epochs: 25
      novelty_detector: # Classification + Clustering
        WindowedMeanKLDiv:
          kl_threshold: 5.365822113508410
          kl_threshold_decay_rate: 0.6
          mean_train: 1.0
          std_dev_train: 0.1242729408792351
          window_size: 100
          num_rounds: 40
          #threshold_scale: 3.0 # Hack to scale down early detection.
          #feedback_weight: 1.0 # binary novelty feedback

      # TODO checkpoints for saving the model results.
  #measures:
  #  per_step:
  #    - acc
  #    - top-5 acc
  #    - loss
  #    - mcc
  #    - nmi
  #    #- novelty_detection: # TODO
  #    #  ConfusionMatrix:
  #  cummulative:
  #    - novelty_detection # TODO
  #    - acc
  #    - top-5 acc
  #    - loss
  #    - mcc
  #    - nmi
