# The Open World Human Activity Recognition pipeline from given features
# extracted from a feature representaiton model to the end. This will probably
# be broken down into smaller chunks for convenience.

docstr:
  style: numpy
  from import:
    arn.data.kinetics_owl:
      - DataSplits
      - KineticsOWL
      - KineticsOWLExperiment
    arn.data.kinetics_unified:
      - KineticsUnifiedFeatures
      - KineticsSplitConfig
      - KineticsUnifiedSubset
      - LabelConfig
      - KineticsRootDirs
    arn.models.fine_tune:
      - FineTune
      - FineTuneFC
    arn.models.novelty_detector:
      - WindowedMeanKLDiv
    arn.models.owhar:
      - OWHAPredictor
  #import:
  #  - torch
  # config: # TODO add configuration file linking for convenience
  #   TimeSformer_features_dataloader: abs/path/to/the/config_file.yaml
  main: run #KineticsOWL.run
  configs: # Docstr's beginnings towards config linking. See tag w/ name below
    shared_data_kwargs:
      annotation_path: /home/prijatelj/workspace/research/osr/repos/har/data/analysis/kinetics/kinetics_400_600_700_2020.csv
      kinetics_class_map: /home/prijatelj/workspace/research/osr/repos/har/data/k700_k400_par_class_map.csv
      sample_dirs:
        KineticsRootDirs:
          kinetics400_dir: x3d-features-k400/
          kinetics600_dir: x3d-features-k600/
          kinetics700_2020_dir: x3d-features-k700_2020/
          root_dir: /mnt/hdd/workspace/research/osr/har/kitware/
      device: cuda
      dtype: float32
      subset:
        KineticsUnifiedSubset:
          labels:
            LabelConfig:
              name: 'label_kinetics400'
              known: True

KineticsOWL: # Pipeline for the Open World Learning Data process
  seed: 0 # TODO is this even used?
  environment:
    KineticsOWLExperiment:
      start:
        DataSplits:
          train:
            KineticsUnifiedFeatures: !docstr.configs:shared_data_kwargs
              subset:
                KineticsUnifiedSubset:
                  kinetics400:
                    KineticsSplitConfig:
                      train: True
          val:
            KineticsUnifiedFeatures: !docstr.configs:shared_data_kwargs
              subset:
                KineticsUnifiedSubset:
                  kinetics400:
                    KineticsSplitConfig:
                      validate: True
          test:
            KineticsUnifiedFeatures: !docstr.configs:shared_data_kwargs
              subset:
                KineticsUnifiedSubset:
                  kinetics400:
                    KineticsSplitConfig:
                      test: True
    #label_id: 'kinetics700_map' # TODO check if any k400 are cut. or other changes.
      #measures:
      #  per_step:
      #    - acc
      #    - top-5 acc
      #    - loss
      #    - mcc
      #    - nmi
      #    #- novelty_detection: # TODO
      #    #  ConfusionMatrix:
      #  cummulative:
      #    - novelty_detection # TODO
      #    - acc
      #    - top-5 acc
      #    - loss
      #    - mcc
      #    - nmi
  predictor:
    OWHAPredictor: # the Open World Agent
      fine_tuning:
        FineTune:
          model:
            FineTuneFC:
              input_size: 512
              width: 512
              depth: 5
              dropout: 0.5
          batch_size: 1000
          epochs: 25
      novelty_detector: # Classification + Clustering
        WindowedMeanKLDiv:
          kl_threshold: 5.365822113508410
          kl_threshold_decay_rate: 0.6
          mean_train: 1.0
          std_dev_train: 0.1242729408792351
          window_size: 100
          num_rounds: 40
          #threshold_scale: 3.0 # Hack to scale down early detection.
          #feedback_weight: 1.0 # binary novelty feedback
      # TODO checkpoints for saving the model results.
