FROM nvcr.io/nvidia/pytorch:19.02-py3

# Set a working directory for the app
WORKDIR /tmp/container_workspaces/docker/luke/

# Copy all the files to the container
COPY . .

# TODO intall dependencies
# TODO conda?
# TODO python requirements
# TODO EVM
# TODO X3D, if not included in this package
# TODO CLIP, if not included in this package

# TODO intall this package
